package Mazzard.Components;

public enum BasicEnums {
    ANIMATION_ATTACK,
    ANIMATION_JUMP,
    ANIMATION_IDLE,
    ANIMATION_RUN,

    MENUSTATE_MAIN,
    MENUSTATE_SETTINGS,
    MENUSTATE_HELP,

    SETTINGS_SOUNDS,
    SETTINGS_CONTROLS,
    SETTINGS_FULLSCREEN,
    SETTINGS_HITBOXES,

    PLAYSTATE_PLAYING,
    PLAYSTATE_PASSED,
    PLAYSTATE_WON,
    PLAYSTATE_FAILED
}
